name: Docker Image CI for GHCR

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            #- name: Set up QEMU
            #  uses: docker/setup-qemu-action@v2

            #- name: Set up Docker Buildx
            #  uses: docker/setup-buildx-action@v1

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GHP }}

            - name: Build and push the image
              run: |
                  docker build . -t ghcr.io/${{ github.repository_owner }}/fast-api-template:latest
                  docker push ghcr.io/${{ github.repository_owner }}/fast-api-template:latest
               

            #- name: Build and push
            #  uses: docker/build-push-action@v2
            #  with:
            #      context: .
            #      file: ./Dockerfile
            #      platforms: linux/amd64,linux/arm64
            #      push: true
            #      tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:latest
            #      labels: org.opencontainers.image.source=